# Generated by Django 4.0.2 on 2022-02-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accessCard',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plant',
            field=models.CharField(default='SA', max_length=2),
        ),
    ]
