# Generated by Django 4.0.2 on 2022-02-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_accesscard_customuser_plant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='accessCard',
            new_name='access_card',
        ),
    ]
